package com.quickstack.product.service;

/**
 * Audit actions for catalog operations.
 */
public enum CatalogAction {
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    CATEGORY_RESTORED,
    CATEGORY_REORDERED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_RESTORED,
    PRODUCT_AVAILABILITY_CHANGED,
    PRODUCT_REORDERED,
    VARIANT_ADDED,
    VARIANT_UPDATED,
    VARIANT_DELETED,
    MODIFIER_GROUP_CREATED,
    MODIFIER_GROUP_UPDATED,
    MODIFIER_GROUP_DELETED,
    MODIFIER_ADDED,
    MODIFIER_UPDATED,
    MODIFIER_DELETED,
    COMBO_CREATED,
    COMBO_UPDATED,
    COMBO_DELETED
}
